### ISSUE TITLE
[BUG] Odamex won't build on ArchLinux with CMake 3.20.5/GCC 11.1

### ISSUE THREAD

**Issue by jjbarr** [odamex/odamex#421]
**Describe the bug**

I'm unclear about where this is coming from, but on my system, Odamex is being built with -Werror=format-security (probably a default in CMake or GCC). As a result, Odamex fails to build. 

**Build that the bug occurred in**

Occured while trying to build Odamex 0.9.3

**To Reproduce**

Attempt to build the engine (probably with latest CMake and GCC, although I'm not entirely sure of the exact culprit sadly)

**Expected behavior**

The game would build.

**Screenshots, NetDemos, & Crash Dumps**

The salient log lines are as follows (with my username removed...)

```
/<...>/odamex/src/odamex-src-0.9.3/client/src/cl_main.cpp:3075:15: error: format not a string literal and no format arguments [-Werror=format-security]
 3075 |         Printf(buf.c_str());
      |         ~~~~~~^~~~~~~~~~~~~
...
/<...>/odamex/src/odamex-src-0.9.3/client/src/cl_main.cpp:4436:31: error: format not a string literal and no format arguments [-Werror=format-security]
 4436 |                         Printf(PRINT_HIGH, ss.str().c_str());
      |                         ~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Additional context**

Assuming, of course, that Printf works the same as POSIX standard, the obvious solution applies in the first case. In the second case, I haven't got a clue why PRINT_HIGH is tripping the warning, since there are other instances of it in the file and it's a presumably a constant (?). Frankly, I'm not familiar enough with the code base (I'm not familiar with it at all), so I defer to people who know what they're doing on how to fix this.

**Comment by leximayfield** [comment]
This default is actually coming from Arch Linux proper.  That said, the problems this flag point out are valid, so if it's good enough for Arch, it's good enough for us.

Please give 7e707b8 a spin and let me know if you run into issues.

**Comment by sashaaaaaaaaa** [comment]
The cl_parse.cpp doesn't exist anymore and with the other changes made there's still these two:

```
/home/s/aur/myown/odamex-git/src/odamex/client/src/cl_main.cpp:3075:15: error: format not a string literal and no format arguments [-Werror=format-security]
 3075 |         Printf(buf.c_str());
      |

/home/s/aur/myown/odamex-git/src/odamex/client/src/cl_main.cpp:4436:31: error: format not a string literal and no format arguments [-Werror=format-security]
 4436 |         Printf(PRINT_HIGH, ss.str().c_str());
      |
```

**Comment by rakohus** [comment]
Any updates here?

**Comment by rakohus** [comment]
@jjbarr @sashaaaaaaaaa could either of you provide an update?

**Comment by jjbarr** [comment]
Unfortunately I'm away from my Arch system right now, so it's difficult for me to test this.

To my recollection it had not yet been fixed when last I tried, but that was over a month ago, I believe.

**Comment by bcahue** [comment]
I don't see any format-security warnings when building with GCC on current `stable` so I am closing this for now. Please comment if you cannot build on Arch still.

**Comment by sashaaaaaaaaa** [comment]
Sorry I'm late but yeah it's fine now.
